"""Create portable CP2K calculation packages."""

from __future__ import annotations

from pathlib import Path

from pymatgen.core import Structure

from nsdw.calculators.cp2k.generation_models import (
    CP2KInputConfig,
)
from nsdw.calculators.cp2k.generator import (
    render_cp2k_input,
)
from nsdw.structures.writer import write_xyz


class CP2KPackageError(RuntimeError):
    """Raised when NSDW cannot create a CP2K calculation package."""


def write_cp2k_package(
    *,
    structure: Structure,
    config: CP2KInputConfig,
    output_directory: str | Path,
    input_filename: str | None = None,
    coordinate_filename: str | None = None,
) -> Path:
    """Write a portable CP2K input and matching external XYZ file."""

    output_directory = (
        Path(output_directory)
        .expanduser()
        .resolve()
    )

    if output_directory.exists() and not output_directory.is_dir():
        raise CP2KPackageError(
            "CP2K package output path exists and is not "
            f"a directory: {output_directory}"
        )

    if input_filename is None:
        input_filename = f"{config.project_name}.inp"

    if coordinate_filename is None:
        coordinate_filename = f"{config.project_name}.xyz"

    input_name = Path(input_filename)

    coordinate_name = Path(coordinate_filename)

    if input_name.name != input_filename:
        raise CP2KPackageError(
            "input_filename must be a filename, not a path."
        )

    if coordinate_name.name != coordinate_filename:
        raise CP2KPackageError(
            "coordinate_filename must be a filename, not a path."
        )

    if input_name.suffix.lower() != ".inp":
        raise CP2KPackageError(
            "CP2K input filename must end in '.inp'."
        )

    if coordinate_name.suffix.lower() != ".xyz":
        raise CP2KPackageError(
            "CP2K coordinate filename must end in '.xyz'."
        )

    input_path = output_directory / input_name
    coordinate_path = output_directory / coordinate_name

    if input_path.exists():
        raise CP2KPackageError(
            f"CP2K input already exists: {input_path}"
        )

    if coordinate_path.exists():
        raise CP2KPackageError(
            "CP2K coordinate file already exists: "
            f"{coordinate_path}"
        )

    resolved_config = config.model_copy(
        update={
            "coordinate_file": coordinate_name.name,
            "coordinate_file_format": "XYZ",
        }
    )

    # Validate and render the complete CP2K input before writing
    # anything to disk. This prevents failed generation from
    # leaving behind a partial calculation package.
    input_text = render_cp2k_input(
        config=resolved_config,
        structure=structure,
    )

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    try:
        write_xyz(
            structure=structure,
            path=coordinate_path,
            comment=(
                "Generated by NSDW for "
                f"{resolved_config.project_name}"
            ),
        )

        input_path.write_text(
            input_text,
            encoding="utf-8",
        )

    except Exception as exc:
        # Package creation is all-or-nothing. Remove anything
        # written during this attempt.
        try:
            input_path.unlink(
                missing_ok=True,
            )
        except OSError:
            pass

        try:
            coordinate_path.unlink(
                missing_ok=True,
            )
        except OSError:
            pass

        if isinstance(
            exc,
            CP2KPackageError,
        ):
            raise

        raise CP2KPackageError(
            "Could not write CP2K calculation package "
            f"to '{output_directory}': {exc}"
        ) from exc

    return output_directory