"""Deterministic structure writers used by NSDW workflows."""

from __future__ import annotations

from pathlib import Path

from pymatgen.core import Structure


class StructureWriteError(RuntimeError):
    """Raised when NSDW cannot write a structure file."""


def render_xyz(
    structure: Structure,
    comment: str = "Generated by NSDW",
) -> str:
    """Render a pymatgen Structure as standard Cartesian XYZ."""

    if len(structure) == 0:
        raise StructureWriteError(
            "Cannot write an empty structure."
        )

    lines = [
        str(len(structure)),
        comment,
    ]

    for site in structure:
        symbol = site.specie.symbol
        x, y, z = site.coords

        lines.append(
            f"{symbol:<3} "
            f"{x:.12f} "
            f"{y:.12f} "
            f"{z:.12f}"
        )

    return "\n".join(lines) + "\n"


def write_xyz(
    structure: Structure,
    path: str | Path,
    comment: str = "Generated by NSDW",
) -> Path:
    """Write a pymatgen Structure as standard Cartesian XYZ."""

    output_path = Path(path).expanduser().resolve()

    if output_path.exists() and output_path.is_dir():
        raise StructureWriteError(
            f"XYZ output path is a directory: {output_path}"
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    text = render_xyz(
        structure=structure,
        comment=comment,
    )

    try:
        output_path.write_text(
            text,
            encoding="utf-8",
        )
    except OSError as exc:
        raise StructureWriteError(
            f"Could not write XYZ file '{output_path}': {exc}"
        ) from exc

    return output_path
